import { AcademyVideoCourse } from "@/lib/types";

export const mockAcademyVideoCourses: AcademyVideoCourse[] = [
  // 1. หมวดนักกีฬาเยาวชน (ตรงกับ Image 3: Basketball Fundamental Skills)
  {
    id: "course-fund-01",
    category: "ATHLETE_DEVELOPMENT",
    categoryDisplay: "หลักสูตรและคลินิกสำหรับนักกีฬาเยาวชน",
    title: "Basketball Fundamental Skills ทักษะบาสเกตบอลระดับพื้นฐาน",
    subtitle: "ฝึกทักษะบาสเกตบอลด้วยตัวเอง ตั้งแต่การเลี้ยงบอล การยิง และฟุตเวิร์กที่ถูกต้องตามหลักสากล",
    instructorName: "โค้ชเอก กิตติศักดิ์ (หัวร้อน บาสเกตบอล)",
    instructorTitle: "อดีตนักกีฬาทีมชาติไทย & ผู้ก่อตั้ง HuaRon Academy",
    instructorAvatar:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    instructorBadge: "BSAT CERTIFIED COACH A-LICENSE",
    priceThb: 690,
    originalPriceThb: 1290,
    isFree: false,
    rating: 4.7,
    reviewCount: 3,
    duration: "4 ชั่วโมง 45 นาที",
    level: "BEGINNER",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=800&q=80",
    videoPreviewUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    lessonsCount: 14,
    enrolledCount: 342,
    createdByRole: "COACH",
    createdAt: "2026-09-10",
    keyOutcomes: [
      "ท่าทางชูตบาสที่ถูกต้อง (B.E.E.F. Principles)",
      "ฟุตเวิร์กเบื้องต้น Drop Step, Jab Step, และ Rip Through",
      "การเลี้ยงบอลคอนโทรลสองมือโดยไม่ต้องก้มมองบอล",
      "การเลย์อัปทั้งมือซ้ายและขวาอย่างมั่นใจ",
    ],
    equipmentNeeded: ["ลูกบาสเกตบอล 1 ลูก", "กรวยฝึกซ้อม 4 อัน", "พื้นที่แป้นบาสครึ่งสนาม"],
    syllabus: [
      {
        id: "l-1",
        title: "บทนำ: สรีระการยืนและการจัดระเบียบร่างกาย (Stance & Balance)",
        duration: "12:40",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        isFreePreview: true,
      },
      {
        id: "l-2",
        title: "Stationary Ball Handling: การเลี้ยงบอลต่ำ-สูง และ Figure 8",
        duration: "18:25",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        isFreePreview: true,
      },
      {
        id: "l-3",
        title: "Crossover & Between the Legs: จังหวะเปลี่ยนทิศทางแบบไม่เสียการทรงตัว",
        duration: "22:10",
        isFreePreview: false,
      },
      {
        id: "l-4",
        title: "Form Shooting 101: การสะบัดข้อมือ Follow Through ให้บอลหมุน Backspin",
        duration: "25:40",
        isFreePreview: false,
      },
      {
        id: "l-5",
        title: "Layup Mastery: ทักษะก้าวขา 1-2 สองจังหวะมือซ้ายและขวา",
        duration: "20:15",
        isFreePreview: false,
      },
    ],
  },
  {
    id: "course-fund-02",
    category: "ATHLETE_DEVELOPMENT",
    categoryDisplay: "หลักสูตรและคลินิกสำหรับนักกีฬาเยาวชน",
    title: "Elite Shooting Mechanics: สูตรลับซ้อมชูต 500 ลูกสร้างความแม่นยำถาวร",
    subtitle: "เจาะลึกองศาข้อศอก จุดปล่อยบอลสูงสุด และการสร้างกล้ามเนื้อจดจำ (Muscle Memory)",
    instructorName: "โค้ชธีรพงศ์ อัศวชัย",
    instructorTitle: "Head Coach โรงเรียนกรุงเทพคริสเตียนวิทยาลัย",
    instructorAvatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    instructorBadge: "CHAMPIONSHIP COACH 2025",
    priceThb: 890,
    originalPriceThb: 1590,
    isFree: false,
    rating: 4.9,
    reviewCount: 18,
    duration: "3 ชั่วโมง 30 นาที",
    level: "INTERMEDIATE",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1519766304817-4f37bda74a29?auto=format&fit=crop&w=800&q=80",
    videoPreviewUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    lessonsCount: 10,
    enrolledCount: 512,
    createdByRole: "COACH",
    createdAt: "2026-09-12",
    keyOutcomes: [
      "Catch & Shoot เทคนิคจับบอลพร้อมยิงใน 0.7 วินาที",
      "การปรับองศา Release Point ให้ทนทานต่อแรงกดดันตัวประกบ",
      "ตารางโปรแกรมซ้อมยิง 500 ลูกต่อวันพร้อมใบบันทึกผล",
    ],
    equipmentNeeded: ["ลูกบาสเกตบอล 2 ลูก", "คู่ซ้อมรีบาวด์ 1 คน", "สนามบาสเกตบอลมาตรฐาน"],
    syllabus: [
      {
        id: "s-1",
        title: "จุดปล่อยบอลและการถ่ายแรงจากปลายเท้าสู่ปลายนิ้ว (Kinetic Chain)",
        duration: "15:20",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        isFreePreview: true,
      },
      {
        id: "s-2",
        title: "Mid-Range Pull-Up: จังหวะกระโดดหยุดยิงหลังจากเลี้ยง 1-2 ครั้ง",
        duration: "21:30",
        isFreePreview: false,
      },
      {
        id: "s-3",
        title: "3-Point Range Extension: ขยายระยะยิงสามแต้มโดยไม่ต้องออกแรงเหวี่ยงแขน",
        duration: "28:10",
        isFreePreview: false,
      },
    ],
  },

  // 2. หมวดสำหรับโต๊ะกรรมการ & สถิติ (Table Officials & Statisticians)
  {
    id: "course-table-01",
    category: "TABLE_OFFICIALS",
    categoryDisplay: "หลักสูตรสำหรับโต๊ะกรรมการ & สถิติ",
    title: "FIBA LiveStats & Table Official Digital Console Masterclass",
    subtitle: "หลักสูตรมาตรฐานสมาคมกีฬาบาสเกตบอลแห่งประเทศไทย เพื่อปฏิบัติหน้าที่ในทัวร์นาเมนต์ทางการ",
    instructorName: "อาจารย์สมเกียรติ สถิติมงคล",
    instructorTitle: "หัวหน้าฝ่ายเทคนิคและสถิติ สมาคมกีฬาบาสเกตบอลแห่งประเทศไทย (BSAT)",
    instructorAvatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    instructorBadge: "FIBA INTERNATIONAL COMMISIONER",
    priceThb: 0,
    originalPriceThb: 1500,
    isFree: true,
    rating: 5.0,
    reviewCount: 45,
    duration: "6 ชั่วโมง 15 นาที",
    level: "ALL_LEVELS",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80",
    videoPreviewUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    lessonsCount: 18,
    enrolledCount: 890,
    createdByRole: "ADMIN",
    createdAt: "2026-08-20",
    keyOutcomes: [
      "การใช้งานระบบ StatCourt Console & FIBA LiveStats ครบทุกฟังก์ชัน",
      "กติกา 24 วินาที Shot Clock และการรีเซ็ตเป็น 14 วินาทีตามกติกาใหม่",
      "การประสานงานสัญญาณมือกับผู้ตัดสินในสนาม 3 คน",
      "สิทธิ์สอบรับเข็ม 'Certified Table Official Level 1'",
    ],
    equipmentNeeded: ["คอมพิวเตอร์แล็ปท็อป หรือ iPad", "สัญญาณอินเทอร์เน็ต"],
    syllabus: [
      {
        id: "t-1",
        title: "บทบาทหน้าที่ของคณะกรรมการโต๊ะเทคนิค 4 ตำแหน่งตามกติกา FIBA",
        duration: "20:00",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        isFreePreview: true,
      },
      {
        id: "t-2",
        title: "ระบบบันทึกใบคะแนนดิจิทัล (Digital Scoresheet Protocol)",
        duration: "35:40",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        isFreePreview: true,
      },
      {
        id: "t-3",
        title: "การนับสถิติขั้นสูง: Assist Definition, Blocked Shot vs Missed Shot",
        duration: "40:10",
        isFreePreview: false,
      },
    ],
  },
  {
    id: "course-table-02",
    category: "TABLE_OFFICIALS",
    categoryDisplay: "หลักสูตรสำหรับโต๊ะกรรมการ & สถิติ",
    title: "Shot Clock 24/14 วินาที & การจับเวลาระดับการแข่งขันมาตรฐาน",
    subtitle: "เจาะลึกกรณีศึกษาภาพช้า วินาทีหมดเวลา และการแก้ปัญหานาฬิกาผิดพลาดระหว่างเกม",
    instructorName: "ชัชวาลย์ รัตนไพศาล",
    instructorTitle: "ผู้ตัดสินระดับ FIBA National Referee",
    instructorAvatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80",
    instructorBadge: "FIBA REFEREE LICENSE",
    priceThb: 450,
    originalPriceThb: 990,
    isFree: false,
    rating: 4.8,
    reviewCount: 12,
    duration: "2 ชั่วโมง 50 นาที",
    level: "INTERMEDIATE",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=800&q=80",
    videoPreviewUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    lessonsCount: 8,
    enrolledCount: 215,
    createdByRole: "ADMIN",
    createdAt: "2026-09-01",
    keyOutcomes: [
      "กรณีบอลแตะห่วงแต่ไม่ลงห่วง รีเซ็ต 14 วินาทีในแดนหน้า",
      "การปรับจังหวะเวลากรณีฟาวล์เทคนิคและฟาวล์ผิดวิสัยนักกีฬา",
    ],
    equipmentNeeded: ["นาฬิกาจับเวลา หรือโปรแกรมจำลอง"],
    syllabus: [
      {
        id: "tc-1",
        title: "กติกา Shot Clock 14 วินาทีภาคปฏิบัติ",
        duration: "18:40",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        isFreePreview: true,
      },
    ],
  },

  // 3. หมวดโค้ชและแท็กติก (Coaching & Tactical Essentials)
  {
    id: "course-coach-01",
    category: "COACHING_TACTICS",
    categoryDisplay: "หลักสูตรโค้ชและแท็กติก",
    title: "Modern Pick & Roll Mastery: การวางโครงสร้างเกมรุกสเปซซิ่งยุคใหม่",
    subtitle: "กลยุทธ์การเล่น Spain PnR, Horns Set, และการอ่าน Coverages เกมรับ Drop vs Blitz",
    instructorName: "โค้ชมานพ ชลประทาน",
    instructorTitle: "อดีตผู้ช่วยผู้ฝึกสอนทีมชาติไทย & วิทยากรโค้ช BSAT",
    instructorAvatar:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80",
    instructorBadge: "FIBA COACH LEVEL 2",
    priceThb: 1190,
    originalPriceThb: 2200,
    isFree: false,
    rating: 4.9,
    reviewCount: 27,
    duration: "5 ชั่วโมง 10 นาที",
    level: "ADVANCED",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80",
    videoPreviewUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    lessonsCount: 16,
    enrolledCount: 420,
    createdByRole: "COACH",
    createdAt: "2026-08-28",
    keyOutcomes: [
      "การออกแบบเซ็ตเพลย์ 5 รูปแบบที่เจาะเกมรับ Man-to-Man ได้ผลที่สุด",
      "การสอนตำแหน่งโรลเลอร์ (Short Roll vs Rim Run)",
      "แบบฝึกการสเปซซิ่งมุมคอร์ท 45 องศาเพื่อเปิดเลนไดรฟ์",
    ],
    equipmentNeeded: ["กระดานแท็กติก", "ผู้เล่น 10 คนสำหรับซ้อม 5v5"],
    syllabus: [
      {
        id: "c-1",
        title: "หลักการ Spacing 5 จุดรอบนอก และมุมของ Screen Angle",
        duration: "25:30",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        isFreePreview: true,
      },
      {
        id: "c-2",
        title: "Spain Action: การตั้ง Backscreen ซ้อนเพื่อทำลาย Drop Coverage",
        duration: "32:15",
        isFreePreview: false,
      },
    ],
  },
  {
    id: "course-coach-02",
    category: "COACHING_TACTICS",
    categoryDisplay: "หลักสูตรโค้ชและแท็กติก",
    title: "Zone Defense Breakdown & 1-3-1 Half-Court Trap Blueprint",
    subtitle: "แท็กติกการกดดันตัดบอลกลางสนาม และการซ้อนพื้นที่เกมรับที่เปลี่ยนเกมได้ทันที",
    instructorName: "โค้ชภานุวัฒน์ วิทยาชัย",
    instructorTitle: "Head Coach แชมป์เยาวชนแห่งชาติ 3 สมัย",
    instructorAvatar:
      "https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=400&q=80",
    instructorBadge: "NATIONAL CHAMPION COACH",
    priceThb: 790,
    originalPriceThb: 1490,
    isFree: false,
    rating: 4.8,
    reviewCount: 15,
    duration: "3 ชั่วโมง 40 นาที",
    level: "INTERMEDIATE",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1504450758481-7338eba7524a?auto=format&fit=crop&w=800&q=80",
    videoPreviewUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    lessonsCount: 11,
    enrolledCount: 290,
    createdByRole: "COACH",
    createdAt: "2026-09-05",
    keyOutcomes: [
      "การวางกับดัก Trap บริเวณมุมสนามและเส้นข้าง",
      "การโรเตชันตัวป้องกันใต้แป้นเมื่อบอลถูกส่งเข้า High Post",
    ],
    equipmentNeeded: ["สนามบาสเกตบอล", "ผู้เล่น 5 คน"],
    syllabus: [
      {
        id: "z-1",
        title: "โครงสร้างการยืนตำแหน่ง 1-3-1 และกฎการวิ่งดักบอล",
        duration: "22:10",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        isFreePreview: true,
      },
    ],
  },

  // 4. หมวดวิทยาศาสตร์การกีฬาและการแพทย์ (Sports Science & Athletic Performance)
  {
    id: "course-science-01",
    category: "SPORTS_SCIENCE",
    categoryDisplay: "หมวดวิทยาศาสตร์การกีฬาและการแพทย์",
    title: "Vertical Jump Explosiveness: โปรแกรมเพิ่มแรงกระโดดแบบ Plyometrics",
    subtitle: "แบบฝึกเสริมพลังกล้ามเนื้อขาและเอ็นร้อยหวาย เพิ่มความสูงในการลอยตัวอย่างปลอดภัย",
    instructorName: "อ.ภาคภูมิ กายภาพบำบัด (M.Sc. Sports Science)",
    instructorTitle: "ผู้เชี่ยวชาญด้านเวชศาสตร์การกีฬา & สรีรวิทยาการออกกำลังกาย",
    instructorAvatar:
      "https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=80",
    instructorBadge: "CSCS CERTIFIED S&C SPECIALIST",
    priceThb: 990,
    originalPriceThb: 1890,
    isFree: false,
    rating: 4.9,
    reviewCount: 34,
    duration: "4 ชั่วโมง 10 นาที",
    level: "ALL_LEVELS",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80",
    videoPreviewUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    lessonsCount: 12,
    enrolledCount: 680,
    createdByRole: "ADMIN",
    createdAt: "2026-08-15",
    keyOutcomes: [
      "เพิ่มความสูง Vertical Jump เฉลี่ย 3-5 นิ้ว ภายใน 8 สัปดาห์",
      "การทดสอบ Force Plate และการวัดค่า RSI (Reactive Strength Index)",
      "เทคนิคการลงสู่พื้น (Landing Mechanics) เพื่อลดแรงกระแทกเข่า 60%",
    ],
    equipmentNeeded: ["กล่องกระโดด Plyo Box (30-45 cm)", "ยางยืด Resistance Band", "บาร์เบล"],
    syllabus: [
      {
        id: "v-1",
        title: "หลักสรีรวิทยาของการกระโดด: Stretch-Shortening Cycle (SSC)",
        duration: "19:40",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        isFreePreview: true,
      },
      {
        id: "v-2",
        title: "Landing Mechanics 101: การซับแรงกระแทกด้วยกล้ามเนื้อสะโพก",
        duration: "24:10",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        isFreePreview: true,
      },
      {
        id: "v-3",
        title: "Depth Jump & Shock Method: แบบฝึกระดับสูงเพื่อลด Ground Contact Time",
        duration: "30:45",
        isFreePreview: false,
      },
    ],
  },
  {
    id: "course-science-02",
    category: "SPORTS_SCIENCE",
    categoryDisplay: "หมวดวิทยาศาสตร์การกีฬาและการแพทย์",
    title: "ACL & Ankle Injury Prevention: เกราะป้องกันข้อเท้าพลิกและเอ็นไขว้หน้าเข่า",
    subtitle: "แบบฝึกเสริมความมั่นคงของข้อต่อ และการตรวจคัดกรองความเสี่ยงการบาดเจ็บในนักกีฬาเยาวชน",
    instructorName: "พญ.สิริรัตน์ แพทย์เวชศาสตร์การกีฬา",
    instructorTitle: "แพทย์ที่ปรึกษาสมาคมกีฬาบาสเกตบอลแห่งประเทศไทย",
    instructorAvatar:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
    instructorBadge: "SPORTS MEDICINE CONSULTANT",
    priceThb: 0,
    originalPriceThb: 1200,
    isFree: true,
    rating: 5.0,
    reviewCount: 41,
    duration: "2 ชั่วโมง 45 นาที",
    level: "ALL_LEVELS",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80",
    videoPreviewUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    lessonsCount: 9,
    enrolledCount: 920,
    createdByRole: "ADMIN",
    createdAt: "2026-09-02",
    keyOutcomes: [
      "ท่าบริหารกล้ามเนื้อรอบข้อเท้า (Peroneal Muscles) ป้องกันข้อเท้าพลิกซ้ำซาก",
      "การตรวจมุม Valgus Collapse ของหัวเข่าระหว่างการชะลอความเร็ว (Deceleration)",
      "โปรแกรม Warm-up 10 นาทีสไตล์ FIFA 11+ / FIBA Injury Prevention",
    ],
    equipmentNeeded: ["แผ่นบาลานซ์ Balance Board", "ยางยืด Loop Band"],
    syllabus: [
      {
        id: "acl-1",
        title: "กลไกการบาดเจ็บ Non-Contact ACL ในกีฬาบาสเกตบอล",
        duration: "16:20",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        isFreePreview: true,
      },
      {
        id: "acl-2",
        title: "Single Leg Deceleration Drills: การเบรกและเปลี่ยนทิศทางอย่างปลอดภัย",
        duration: "26:30",
        isFreePreview: true,
      },
    ],
  },
];
