import {
  AcademicRecord,
  TargetUniversityWish,
  ScoutProfileViewItem,
  OpportunityPosting,
  HighlightClipItem,
} from "@/lib/types";

// ==========================================
// 1. ACADEMIC & GPAX TRACKER MOCK DATA
// ==========================================

export const mockAcademicRecords: Record<string, { records: AcademicRecord[]; gpax: number; honorsStatus: string }> = {
  "ath-1": {
    gpax: 3.68,
    honorsStatus: "HIGH HONORS & ACADEMICALLY ELIGIBLE",
    records: [
      {
        id: "acad-1-1",
        athleteId: "ath-1",
        schoolYear: 2567,
        gradeLevel: "ม.4",
        semester: 1,
        gpa: 3.62,
        credits: 16.5,
        isVerified: true,
        verifiedBy: "ฝ่ายทะเบียนและประมวลผล ร.ร.กรุงเทพคริสเตียนวิทยาลัย",
      },
      {
        id: "acad-1-2",
        athleteId: "ath-1",
        schoolYear: 2567,
        gradeLevel: "ม.4",
        semester: 2,
        gpa: 3.70,
        credits: 16.5,
        isVerified: true,
        verifiedBy: "ฝ่ายทะเบียนและประมวลผล ร.ร.กรุงเทพคริสเตียนวิทยาลัย",
      },
      {
        id: "acad-1-3",
        athleteId: "ath-1",
        schoolYear: 2568,
        gradeLevel: "ม.5",
        semester: 1,
        gpa: 3.65,
        credits: 17.0,
        isVerified: true,
        verifiedBy: "ฝ่ายทะเบียนและประมวลผล ร.ร.กรุงเทพคริสเตียนวิทยาลัย",
      },
      {
        id: "acad-1-4",
        athleteId: "ath-1",
        schoolYear: 2568,
        gradeLevel: "ม.5",
        semester: 2,
        gpa: 3.75,
        credits: 17.0,
        isVerified: true,
        verifiedBy: "ฝ่ายทะเบียนและประมวลผล ร.ร.กรุงเทพคริสเตียนวิทยาลัย",
      },
    ],
  },
  "ath-8": {
    gpax: 3.42,
    honorsStatus: "TCAS SPORTS QUOTA ELIGIBLE",
    records: [
      {
        id: "acad-8-1",
        athleteId: "ath-8",
        schoolYear: 2567,
        gradeLevel: "ม.4",
        semester: 1,
        gpa: 3.35,
        credits: 16.0,
        isVerified: true,
        verifiedBy: "ฝ่ายวิชาการ ร.ร.เทพศิรินทร์",
      },
      {
        id: "acad-8-2",
        athleteId: "ath-8",
        schoolYear: 2567,
        gradeLevel: "ม.4",
        semester: 2,
        gpa: 3.48,
        credits: 16.5,
        isVerified: true,
        verifiedBy: "ฝ่ายวิชาการ ร.ร.เทพศิรินทร์",
      },
    ],
  },
};

export const mockTargetUniversities: TargetUniversityWish[] = [
  {
    id: "univ-cu-sport",
    universityName: "จุฬาลงกรณ์มหาวิทยาลัย (Chulalongkorn University)",
    faculty: "คณะวิทยาศาสตร์การกีฬา / สำนักวิชากีฬาและสุขภาพ",
    quotaType: "TCAS รอบที่ 1 Portfolio กีฬาดีเด่นระดับชาติ",
    minGpaxRequired: 2.50,
    currentGpax: 3.68,
    isEligible: true,
    scholarshipCoverage: "ทุนยกเว้นค่าเล่าเรียน 100% + หอพักนักศึกษา + เบี้ยเลี้ยงซ้อม",
    deadlineDate: "2026-11-15",
    notes: "ต้องการหลักฐานสถิติอย่างเป็นทางการจากสมาคมกีฬาบาสเกตบอลแห่งประเทศไทย (BSAT) หรือใบรับรอง StatCourt Certified",
  },
  {
    id: "univ-tu-bba",
    universityName: "มหาวิทยาลัยธรรมศาสตร์ (Thammasat University)",
    faculty: "คณะพาณิชยศาสตร์และการบัญชี / คณะนิติศาสตร์",
    quotaType: "โควตานักเรียนผู้มีความสามารถดีเด่นด้านกีฬา",
    minGpaxRequired: 2.75,
    currentGpax: 3.68,
    isEligible: true,
    scholarshipCoverage: "สิทธิ์คัดเลือกพิเศษเข้าศึกษา + ทุนการศึกษา 50%",
    deadlineDate: "2026-12-05",
    notes: "ต้องผ่านการทดสอบทักษะบาสเกตบอลและสัมภาษณ์เชิงวิชาการ",
  },
  {
    id: "univ-bu-diamond",
    universityName: "มหาวิทยาลัยกรุงเทพ (Bangkok University)",
    faculty: "คณะนิเทศศาสตร์ / คณะบริหารธุรกิจ",
    quotaType: "ทุนประกายเพชรนักกีฬา (Diamond Athletic Scholarship)",
    minGpaxRequired: 2.00,
    currentGpax: 3.68,
    isEligible: true,
    scholarshipCoverage: "ทุนเต็มจำนวน 100% ค่าหน่วยกิตและค่าบำรุงการศึกษา 4 ปีเต็ม",
    deadlineDate: "2026-10-30",
    notes: "การันตีตำแหน่งในทีมมหาวิทยาลัยเข้าแข่งขันรายการกีฬามหาวิทยาลัยแห่งประเทศไทย (Uni Games)",
  },
  {
    id: "univ-ku-eng",
    universityName: "มหาวิทยาลัยเกษตรศาสตร์ (Kasetsart University)",
    faculty: "คณะวิศวกรรมศาสตร์ / คณะเศรษฐศาสตร์",
    quotaType: "โครงการส่งเสริมผู้มีความสามารถพิเศษทางด้านกีฬา",
    minGpaxRequired: 2.50,
    currentGpax: 3.68,
    isEligible: true,
    scholarshipCoverage: "สิทธิ์เข้าศึกษาโดยไม่ต้องสอบข้อเขียนส่วนกลาง",
    deadlineDate: "2027-01-10",
    notes: "พิจารณาแฟ้มสะสมงานและสถิติจากทัวร์นาเมนต์ระดับภูมิภาคขึ้นไป",
  },
];

// ==========================================
// 2. RECRUITMENT VIEWER TRACKER MOCK DATA
// ==========================================

export const mockScoutProfileViews: ScoutProfileViewItem[] = [
  {
    id: "view-1",
    scoutName: "โค้ชสมชาย อุดมทรัพย์",
    scoutRole: "Head Coach & Talent Director",
    institution: "Chulalongkorn University (จุฬาลงกรณ์มหาวิทยาลัย)",
    institutionBadge: "CU",
    viewCount: 6,
    lastViewedAt: "10 นาทีที่แล้ว",
    actionTaken: "VIEWED_FILM",
    isVerifiedScout: true,
  },
  {
    id: "view-2",
    scoutName: "อ.วิชาญ เกียรติวัฒนา",
    scoutRole: "Director of Basketball Operations",
    institution: "Bangkok University (มหาวิทยาลัยกรุงเทพ)",
    institutionBadge: "BU",
    viewCount: 4,
    lastViewedAt: "2 ชั่วโมงที่แล้ว",
    actionTaken: "DOWNLOADED_DOSSIER",
    isVerifiedScout: true,
  },
  {
    id: "view-3",
    scoutName: "Scouting Department",
    scoutRole: "Senior Scout / Youth Development",
    institution: "Hi-Tech Basketball Club (สโมสรไฮเทค)",
    institutionBadge: "HT",
    viewCount: 8,
    lastViewedAt: "เมื่อวานนี้ 19:45",
    actionTaken: "ADDED_TO_SHORTLIST",
    isVerifiedScout: true,
  },
  {
    id: "view-4",
    scoutName: "โค้ชปรีชา รัตนเวช",
    scoutRole: "Assistant Coach & Recruiter",
    institution: "Thammasat University (มหาวิทยาลัยธรรมศาสตร์)",
    institutionBadge: "TU",
    viewCount: 3,
    lastViewedAt: "3 วันที่แล้ว",
    actionTaken: "VIEWED_BIOMETRICS",
    isVerifiedScout: true,
  },
  {
    id: "view-5",
    scoutName: "ฝ่ายพัฒนาความเป็นเลิศทางกีฬา",
    scoutRole: "Recruitment Coordinator",
    institution: "Assumption University (ABAC)",
    institutionBadge: "AU",
    viewCount: 2,
    lastViewedAt: "5 วันที่แล้ว",
    actionTaken: "VIEWED_FILM",
    isVerifiedScout: true,
  },
];

// ==========================================
// 3. TRYOUTS & SCHOLARSHIP OPPORTUNITIES MOCK
// ==========================================

export const mockOpportunities: OpportunityPosting[] = [
  {
    id: "opp-cu-tcas-2026",
    title: "โควตานักกีฬาบาสเกตบอลดีเด่น TCAS รอบที่ 1 Portfolio ปีการศึกษา 2570",
    institution: "จุฬาลงกรณ์มหาวิทยาลัย (Chulalongkorn University)",
    institutionLogo: "CU",
    level: "UNIVERSITY",
    levelDisplay: "ระดับอุดมศึกษา (TCAS รอบ 1)",
    scholarshipType: "FULL_100",
    scholarshipDisplay: "ทุนเต็มจำนวน 100% (รวมหอพักและอุปกรณ์ฝึกซ้อม)",
    province: "กรุงเทพมหานคร",
    region: "BANGKOK",
    deadline: "2026-11-20",
    quotaCount: 6,
    minGpax: 2.00,
    ageRequirement: "กำลังศึกษาชั้น ม.6 หรือเทียบเท่า (เกิดปี 2550 - 2551)",
    stipendNotes: "เบี้ยเลี้ยงฝึกซ้อมประจำเดือน และสิทธิ์การรักษาพยาบาล รพ.จุฬาลงกรณ์",
    status: "OPEN",
    description:
      "เปิดรับสมัครคัดเลือกนักเรียนที่มีความสามารถดีเด่นด้านกีฬาบาสเกตบอลชายและหญิง เข้าศึกษาในจุฬาลงกรณ์มหาวิทยาลัย โดยพิจารณาจากแฟ้มสะสมงานสถิติที่ผ่านการรับรอง และการทดสอบสมรรถภาพทางกาย",
    requirements: [
      "มีผลการเรียนเฉลี่ยสะสม (GPAX) ไม่น้อยกว่า 2.00",
      "มีประวัติการแข่งขันในรายการระดับชาติ หรือทัวร์นาเมนต์ที่รับรองโดย BSAT หรือ StatCourt Certified ย้อนหลัง 2 ปี",
      "มีสถิติการเล่นพร้อมลิงก์คลิปวิดีโอที่สามารถตรวจสอบย้อนกลับได้ (Audit Trail)",
      "ผ่านการตรวจร่างกายและสมรรถภาพทางกายตามเกณฑ์ของศูนย์เวชศาสตร์การกีฬา",
    ],
    contactEmail: "sports-quota@chula.ac.th",
    contactPhone: "02-218-0188",
  },
  {
    id: "opp-tu-quota-2026",
    title: "โครงการคัดเลือกนักเรียนผู้มีความสามารถดีเด่นทางด้านกีฬา มหาวิทยาลัยธรรมศาสตร์",
    institution: "มหาวิทยาลัยธรรมศาสตร์ (Thammasat University)",
    institutionLogo: "TU",
    level: "UNIVERSITY",
    levelDisplay: "ระดับอุดมศึกษา (โควตากีฬา)",
    scholarshipType: "PARTIAL_50",
    scholarshipDisplay: "โควตาเข้าศึกษาคณะยอดนิยม พร้อมทุน 50%",
    province: "ปทุมธานี",
    region: "CENTRAL",
    deadline: "2026-12-10",
    quotaCount: 8,
    minGpax: 2.50,
    ageRequirement: "กำลังศึกษาชั้น ม.6",
    stipendNotes: "โควตาพิเศษคณะพาณิชยศาสตร์ฯ, รัฐศาสตร์, เศรษฐศาสตร์, นิติศาสตร์",
    status: "OPEN",
    description:
      "มอบสิทธิ์คัดเลือกตรงเข้าศึกษาในคณะชั้นนำสำหรับนักกีฬาบาสเกตบอลระดับแถวหน้าของประเทศ เพื่อเข้าร่วมเป็นส่วนหนึ่งของทีมมหาวิทยาลัยธรรมศาสตร์",
    requirements: [
      "GPAX 5 ภาคเรียน ไม่ต่ำกว่า 2.50",
      "เคยติดอันดับ Top 100 บนระบบ StatCourtTH หรือติดตัวแทนจังหวัด/เขตการศึกษา",
      "นำส่งรายงานสถิติ FIBA Box Score และใบรับรอง Digital Pass ประจำตัว",
    ],
    contactEmail: "recruitment@tu.ac.th",
    contactPhone: "02-564-4444 ต่อ 1234",
  },
  {
    id: "opp-bu-diamond-2026",
    title: "ทุนประกายเพชรนักกีฬา (Diamond Athletic Full Scholarship) มหาวิทยาลัยกรุงเทพ",
    institution: "มหาวิทยาลัยกรุงเทพ (Bangkok University)",
    institutionLogo: "BU",
    level: "UNIVERSITY",
    levelDisplay: "ระดับอุดมศึกษา (ทุนช้างเผือก)",
    scholarshipType: "FULL_100",
    scholarshipDisplay: "ทุนการศึกษาเต็มจำนวน 100% ตลอด 4 ปี",
    province: "ปทุมธานี",
    region: "CENTRAL",
    deadline: "2026-10-31",
    quotaCount: 5,
    minGpax: 2.00,
    ageRequirement: "จบ ม.6 หรือเทียบเท่า / ปวช.",
    stipendNotes: "ฟรีค่าเล่าเรียนและค่าธรรมเนียมตลอดหลักสูตร 4 ปี มูลค่ากว่า 450,000 บาท",
    status: "CLOSING_SOON",
    description:
      "ทุนการศึกษาสำหรับนักกีฬาบาสเกตบอลชายฝีมือระดับ Elite เพื่อเสริมทัพทีม Bangkok University คว้าแชมป์บาสเกตบอลมหาวิทยาลัยแห่งประเทศไทย",
    requirements: [
      "มีส่วนสูงไม่น้อยกว่า 185 ซม. (การ์ด/ปีก) หรือ 195 ซม. (เซ็นเตอร์)",
      "มีสถิติ True Shooting (TS%) ไม่ต่ำกว่า 50% หรือค่า FIBA EFF เฉลี่ยเกิน 15 แต้ม",
      "พร้อมเข้าร่วมฝึกซ้อมตามแผนงานของสตาฟฟ์โค้ชมหาวิทยาลัย",
    ],
    contactEmail: "scholarship@bu.ac.th",
    contactPhone: "02-407-3888",
  },
  {
    id: "opp-bcc-changpeuk-2026",
    title: "คัดตัวนักเรียนทุนช้างเผือกบาสเกตบอล ม.4 ประจำปีการศึกษา 2570",
    institution: "โรงเรียนกรุงเทพคริสเตียนวิทยาลัย (Bangkok Christian College)",
    institutionLogo: "BCC",
    level: "HIGH_SCHOOL",
    levelDisplay: "ระดับมัธยมศึกษาตอนปลาย (ม.4)",
    scholarshipType: "FULL_100",
    scholarshipDisplay: "ทุนเรียนฟรี + หอพักนักกีฬา + ค่าอาหาร",
    province: "กรุงเทพมหานคร",
    region: "BANGKOK",
    deadline: "2026-10-15",
    quotaCount: 4,
    minGpax: 2.50,
    ageRequirement: "กำลังศึกษาชั้น ม.3 (อายุไม่เกิน 16 ปี ณ วันแข่งขัน)",
    stipendNotes: "โปรแกรมฝึกซ้อมแบบเข้มข้น และโอกาสแข่งขันรายการระดับประเทศ TOA / กรมพลศึกษา",
    status: "CLOSING_SOON",
    description:
      "โอกาสทองสำหรับเยาวชนนักบาสเกตบอลที่มีความมุ่งมั่น ก้าวเข้าสู่รั้วม่วง-ทอง โรงเรียนมัธยมชั้นนำของประเทศไทย พัฒนาทั้งวิชาการและกีฬาในระดับสูงสุด",
    requirements: [
      "เกิดระหว่าง พ.ศ. 2552 - 2553 (U16)",
      "มีพื้นฐานทักษะบาสเกตบอลขั้นสูง และความเข้าใจแผนการเล่น",
      "มีหนังสือรับรองความประพฤติจากอาจารย์ใหญ่โรงเรียนเดิม",
    ],
    contactEmail: "basketball@bcc.ac.th",
    contactPhone: "02-637-8822",
  },
  {
    id: "opp-act-elite-2026",
    title: "เปิดคัดเลือกนักกีฬาบาสเกตบอลเยาวชน รุ่นอายุ 16 ปี (U16) อัสสัมชัญธนบุรี",
    institution: "โรงเรียนอัสสัมชัญธนบุรี (Assumption College Thonburi)",
    institutionLogo: "ACT",
    level: "HIGH_SCHOOL",
    levelDisplay: "ระดับมัธยมศึกษาตอนปลาย (ม.4)",
    scholarshipType: "FULL_100",
    scholarshipDisplay: "ทุนการศึกษา 100% + หอพักประจำ",
    province: "กรุงเทพมหานคร",
    region: "BANGKOK",
    deadline: "2026-11-05",
    quotaCount: 6,
    minGpax: 2.20,
    ageRequirement: "นักเรียนชาย รุ่นอายุ U16",
    stipendNotes: "ฟิตเนสส่วนตัวและทีมงานกายภาพบำบัดประจำสโมสร",
    status: "OPEN",
    description:
      "คัดเลือกนักกีฬาเพื่อเข้าสังกัดอัสสัมชัญธนบุรี แชมป์บาสเกตบอลเยาวชนระดับประเทศ มีศูนย์ฝึกมาตรฐานสากลและโค้ชต่างชาติประจำการ",
    requirements: [
      "ผ่านการทดสอบสมรรถภาพ Combine: Vertical Jump, Shuttle Run, 3/4 Court Sprint",
      "มีประวัติสถิติและคลิปวิดีโอจากแมตช์จริงบน StatCourtTH",
    ],
    contactEmail: "act-basketball@act.ac.th",
    contactPhone: "02-807-9555",
  },
  {
    id: "opp-hitech-youth-2026",
    title: "Hi-Tech Youth Academy 2026 Open Tryouts (U18)",
    institution: "สโมสรบาสเกตบอลไฮเทค (Hi-Tech Basketball Club)",
    institutionLogo: "HT",
    level: "SEMI_PRO",
    levelDisplay: "สโมสรชั้นนำ / กึ่งอาชีพ",
    scholarshipType: "QUOTA_ONLY",
    scholarshipDisplay: "เบี้ยเลี้ยงซ้อม + เซ็นสัญญาพัฒนาสู่ลีกอาชีพ BTL",
    province: "กรุงเทพมหานคร",
    region: "BANGKOK",
    deadline: "2026-10-25",
    quotaCount: 5,
    ageRequirement: "อายุ 16 - 19 ปี",
    stipendNotes: "ชุดซ้อม, รองเท้าบาสเกตบอล, ประกันอุบัติเหตุ และเบี้ยเลี้ยงต่อแมตช์",
    status: "OPEN",
    description:
      "เวทีคัดตัวสู่สโมสรบาสเกตบอลระดับตำนานของไทย สัมผัสระบบการซ้อมระดับมืออาชีพร่วมกับผู้เล่นทีมชาติไทย และโอกาสได้รับสัญญาผู้เล่นเยาวชนกึ่งอาชีพ",
    requirements: [
      "ทัศนคติดี วินัยสูง พร้อมฝึกซ้อมช่วงเย็นและวันหยุดสุดสัปดาห์",
      "มีค่าตัวชี้วัดความแม่นยำและการอ่านเกมในระดับแข่งขันจริง",
    ],
    contactEmail: "academy@hitechbasketball.com",
    contactPhone: "081-555-9988",
  },
];

// ==========================================
// 4. HIGHLIGHT REEL EVENT CLIPS MOCK
// ==========================================

export const mockHighlightClips: HighlightClipItem[] = [
  {
    id: "clip-1",
    matchId: "match-bcc-ds-01",
    quarter: 1,
    timestampDisplay: "Q1 08:45",
    elapsedSec: 42,
    eventType: "THREE_POINT_MADE",
    title: "Pull-up 3-Pointer in Transition",
    description: "ไดรฟ์ดึงจังหวะจากกึ่งกลางสนาม ยิงลูก 3 แต้มข้ามมือตัวประกบลงอย่างหมดจด",
    durationSec: 8,
    isSelected: true,
  },
  {
    id: "clip-2",
    matchId: "match-bcc-ds-01",
    quarter: 2,
    timestampDisplay: "Q2 04:12",
    elapsedSec: 112,
    eventType: "ASSIST",
    title: "No-Look Pocket Pass to Rolling Big",
    description: "เล่น Pick-and-roll จ่ายบอลทะลุช่องลอดแขนเซ็นเตอร์คู่แข่งให้เพื่อนทำแต้มง่าย",
    durationSec: 7,
    isSelected: true,
  },
  {
    id: "clip-3",
    matchId: "match-bcc-ds-01",
    quarter: 3,
    timestampDisplay: "Q3 01:25",
    elapsedSec: 245,
    eventType: "STEAL",
    title: "Clutch On-Ball Steal & Fastbreak",
    description: "อ่านทางการส่งบอล ดักขโมยบอลกลางอากาศแล้วพุ่งขึ้นเลย์อัพสวนกลับได้ 2 แต้ม",
    durationSec: 10,
    isSelected: true,
  },
  {
    id: "clip-4",
    matchId: "match-bcc-ds-01",
    quarter: 4,
    timestampDisplay: "Q4 05:20",
    elapsedSec: 320,
    eventType: "TWO_POINT_MADE",
    title: "And-One Stepback Mid-range Jumper",
    description: "ใช้ Footwork สเต็ปแบ็กยิงระยะ 18 ฟุตพร้อมเรียกฟาวล์ 1 ช็อต",
    durationSec: 9,
    isSelected: true,
  },
  {
    id: "clip-5",
    matchId: "match-bcc-ds-01",
    quarter: 4,
    timestampDisplay: "Q4 00:48",
    elapsedSec: 410,
    eventType: "THREE_POINT_MADE",
    title: "Game-Sealing Corner 3-Pointer",
    description: "รับบอล Kick-out ยิง 3 แต้มจากมุมคอร์ทปิดกล่องแมตช์คว้าชัยชนะ",
    durationSec: 8,
    isSelected: true,
  },
];
