import type {
  AthleteProfile,
  AthleteSeasonStats,
  Match,
  MatchEvent,
  MarketplaceItem,
  Team,
  Tournament,
} from "../types";

export const mockTournaments: Tournament[] = [
  {
    id: "tourn-toa-2026",
    name: "TOA Youth Basketball League Thailand 2026",
    location: "Nimibutr Stadium, National Stadium Complex, Bangkok",
    startDate: "2026-08-10",
    endDate: "2026-09-28",
    category: "U18",
  },
  {
    id: "tourn-tcas-elite",
    name: "TCAS Elite High School Invitational",
    location: "Chulalongkorn University Sports Complex, Bangkok",
    startDate: "2026-09-01",
    endDate: "2026-10-15",
    category: "U18",
  },
];

export const mockTeams: Team[] = [
  {
    id: "team-bcc",
    name: "Bangkok Christian College",
    shortName: "BCC",
    institution: "Bangkok Christian College, Silom, Bangkok",
    primaryColor: "#4B0082",
    roster: [
      {
        athleteId: "ath-1",
        jerseyNumber: 7,
        firstName: "Thanakorn",
        lastName: "Siriphan",
        position: "POINT_GUARD",
        heightCm: 184,
        fouls: 1,
        points: 18,
        isOnCourt: true,
      },
      {
        athleteId: "ath-2",
        jerseyNumber: 11,
        firstName: "Chayanon",
        lastName: "Wattana",
        position: "SHOOTING_GUARD",
        heightCm: 188,
        fouls: 2,
        points: 12,
        isOnCourt: true,
      },
      {
        athleteId: "ath-3",
        jerseyNumber: 24,
        firstName: "Kittipong",
        lastName: "Rattanachai",
        position: "SMALL_FORWARD",
        heightCm: 195,
        fouls: 3,
        points: 15,
        isOnCourt: true,
      },
      {
        athleteId: "ath-4",
        jerseyNumber: 33,
        firstName: "Warit",
        lastName: "Singhavat",
        position: "POWER_FORWARD",
        heightCm: 198,
        fouls: 2,
        points: 10,
        isOnCourt: true,
      },
      {
        athleteId: "ath-5",
        jerseyNumber: 15,
        firstName: "Bhuripat",
        lastName: "Pongsakorn",
        position: "CENTER",
        heightCm: 204,
        fouls: 1,
        points: 16,
        isOnCourt: true,
      },
      {
        athleteId: "ath-6",
        jerseyNumber: 4,
        firstName: "Saran",
        lastName: "Thongprasert",
        position: "POINT_GUARD",
        heightCm: 180,
        fouls: 0,
        points: 4,
        isOnCourt: false,
      },
      {
        athleteId: "ath-7",
        jerseyNumber: 9,
        firstName: "Nutdanai",
        lastName: "Klinhom",
        position: "SHOOTING_GUARD",
        heightCm: 185,
        fouls: 1,
        points: 2,
        isOnCourt: false,
      },
    ],
  },
  {
    id: "team-debsirin",
    name: "Debsirin School",
    shortName: "DS",
    institution: "Debsirin School, Pom Prap Sattru Phai, Bangkok",
    primaryColor: "#006400",
    roster: [
      {
        athleteId: "ath-8",
        jerseyNumber: 23,
        firstName: "Nattapat",
        lastName: "Sukprasert",
        position: "SHOOTING_GUARD",
        heightCm: 189,
        fouls: 2,
        points: 21,
        isOnCourt: true,
      },
      {
        athleteId: "ath-9",
        jerseyNumber: 3,
        firstName: "Piyawat",
        lastName: "Intarasingh",
        position: "POINT_GUARD",
        heightCm: 182,
        fouls: 3,
        points: 8,
        isOnCourt: true,
      },
      {
        athleteId: "ath-10",
        jerseyNumber: 13,
        firstName: "Phurit",
        lastName: "Charoenwong",
        position: "SMALL_FORWARD",
        heightCm: 193,
        fouls: 1,
        points: 14,
        isOnCourt: true,
      },
      {
        athleteId: "ath-11",
        jerseyNumber: 34,
        firstName: "Teerawat",
        lastName: "Prasertkul",
        position: "POWER_FORWARD",
        heightCm: 199,
        fouls: 2,
        points: 11,
        isOnCourt: true,
      },
      {
        athleteId: "ath-12",
        jerseyNumber: 55,
        firstName: "Anusorn",
        lastName: "Khummuang",
        position: "CENTER",
        heightCm: 202,
        fouls: 4,
        points: 9,
        isOnCourt: true,
      },
      {
        athleteId: "ath-13",
        jerseyNumber: 1,
        firstName: "Korapat",
        lastName: "Wichaidit",
        position: "POINT_GUARD",
        heightCm: 178,
        fouls: 1,
        points: 3,
        isOnCourt: false,
      },
    ],
  },
];

export const mockMatchEvents: MatchEvent[] = [
  {
    id: "ev-1",
    matchId: "match-bcc-ds-01",
    officialId: "off-somchai",
    athleteId: "ath-1",
    teamId: "team-bcc",
    eventType: "THREE_POINT_MADE",
    points: 3,
    quarter: 1,
    gameClockDisplay: "08:45",
    videoElapsedSec: 42,
    isVerified: true,
    createdAt: "2026-09-21T14:15:42Z",
    athleteName: "Thanakorn Siriphan",
    jerseyNumber: 7,
  },
  {
    id: "ev-2",
    matchId: "match-bcc-ds-01",
    officialId: "off-somchai",
    athleteId: "ath-8",
    teamId: "team-debsirin",
    eventType: "TWO_POINT_MADE",
    points: 2,
    quarter: 1,
    gameClockDisplay: "08:12",
    videoElapsedSec: 68,
    isVerified: true,
    createdAt: "2026-09-21T14:16:10Z",
    athleteName: "Nattapat Sukprasert",
    jerseyNumber: 23,
  },
  {
    id: "ev-3",
    matchId: "match-bcc-ds-01",
    officialId: "off-somchai",
    athleteId: "ath-1",
    teamId: "team-bcc",
    eventType: "ASSIST",
    points: 0,
    quarter: 1,
    gameClockDisplay: "07:30",
    videoElapsedSec: 95,
    isVerified: true,
    createdAt: "2026-09-21T14:17:00Z",
    athleteName: "Thanakorn Siriphan",
    jerseyNumber: 7,
  },
  {
    id: "ev-4",
    matchId: "match-bcc-ds-01",
    officialId: "off-somchai",
    athleteId: "ath-5",
    teamId: "team-bcc",
    eventType: "TWO_POINT_MADE",
    points: 2,
    quarter: 1,
    gameClockDisplay: "07:28",
    videoElapsedSec: 97,
    isVerified: true,
    createdAt: "2026-09-21T14:17:02Z",
    athleteName: "Bhuripat Pongsakorn",
    jerseyNumber: 15,
  },
  {
    id: "ev-5",
    matchId: "match-bcc-ds-01",
    officialId: "off-somchai",
    athleteId: "ath-11",
    teamId: "team-debsirin",
    eventType: "BLOCK",
    points: 0,
    quarter: 1,
    gameClockDisplay: "06:14",
    videoElapsedSec: 135,
    isVerified: true,
    createdAt: "2026-09-21T14:18:20Z",
    athleteName: "Teerawat Prasertkul",
    jerseyNumber: 34,
  },
  {
    id: "ev-6",
    matchId: "match-bcc-ds-01",
    officialId: "off-somchai",
    athleteId: "ath-8",
    teamId: "team-debsirin",
    eventType: "THREE_POINT_MADE",
    points: 3,
    quarter: 1,
    gameClockDisplay: "05:40",
    videoElapsedSec: 162,
    isVerified: true,
    createdAt: "2026-09-21T14:19:05Z",
    athleteName: "Nattapat Sukprasert",
    jerseyNumber: 23,
  },
  {
    id: "ev-7",
    matchId: "match-bcc-ds-01",
    officialId: "off-somchai",
    athleteId: "ath-2",
    teamId: "team-bcc",
    eventType: "STEAL",
    points: 0,
    quarter: 1,
    gameClockDisplay: "04:55",
    videoElapsedSec: 198,
    isVerified: true,
    createdAt: "2026-09-21T14:20:12Z",
    athleteName: "Chayanon Wattana",
    jerseyNumber: 11,
  },
  {
    id: "ev-8",
    matchId: "match-bcc-ds-01",
    officialId: "off-somchai",
    athleteId: "ath-10",
    teamId: "team-debsirin",
    eventType: "PERSONAL_FOUL",
    points: 0,
    quarter: 1,
    gameClockDisplay: "03:10",
    videoElapsedSec: 245,
    isVerified: true,
    createdAt: "2026-09-21T14:21:40Z",
    athleteName: "Phurit Charoenwong",
    jerseyNumber: 13,
  },
  {
    id: "ev-9",
    matchId: "match-bcc-ds-01",
    officialId: "off-somchai",
    athleteId: "ath-3",
    teamId: "team-bcc",
    eventType: "THREE_POINT_MADE",
    points: 3,
    quarter: 1,
    gameClockDisplay: "01:20",
    videoElapsedSec: 290,
    isVerified: true,
    createdAt: "2026-09-21T14:23:15Z",
    athleteName: "Kittipong Rattanachai",
    jerseyNumber: 24,
  },
];

export const mockMatch: Match = {
  id: "match-bcc-ds-01",
  tournamentId: "tourn-toa-2026",
  tournamentName: "TOA Youth Basketball League Thailand 2026 - Quarterfinals",
  homeTeamId: "team-bcc",
  homeTeam: mockTeams[0],
  awayTeamId: "team-debsirin",
  awayTeam: mockTeams[1],
  homeScore: 75,
  awayScore: 63,
  currentQuarter: 4,
  gameClockSec: 320, // 05:20 remaining in 4th
  status: "LIVE",
  rawVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
  events: mockMatchEvents,
  createdAt: "2026-09-21T14:00:00Z",
};

export const mockMatches: Match[] = [mockMatch];

export const mockAthleteProfiles: Record<string, AthleteProfile> = {
  "ath-1": {
    id: "ath-1",
    userId: "usr-1",
    firstName: "Thanakorn",
    lastName: "Siriphan",
    birthDate: "2008-04-12",
    primaryPosition: "POINT_GUARD",
    secondaryPosition: "SHOOTING_GUARD",
    heightCm: 184,
    weightKg: 76,
    wingspanCm: 191,
    standingReachCm: 238,
    schoolOrClub: "Bangkok Christian College",
    province: "Bangkok",
    jerseyNumber: 7,
    bio: "Starting floor general for BCC. Elite pick-and-roll navigator with lethal pull-up range. Target: TCAS Sports Quota (Thammasat / Chulalongkorn).",
    avatarUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-BCC-007",
  },
  "ath-8": {
    id: "ath-8",
    userId: "usr-8",
    firstName: "Nattapat",
    lastName: "Sukprasert",
    birthDate: "2008-01-20",
    primaryPosition: "SHOOTING_GUARD",
    secondaryPosition: "SMALL_FORWARD",
    heightCm: 189,
    weightKg: 82,
    wingspanCm: 196,
    standingReachCm: 245,
    schoolOrClub: "Debsirin School",
    province: "Bangkok",
    jerseyNumber: 23,
    bio: "Pure scorer with 3-level shot creation. Leading Debsirin in points and clutch buckets. Thailand U18 National Pool invitee.",
    avatarUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-DS-023",
  },
  "ath-10": {
    id: "ath-10",
    userId: "usr-10",
    firstName: "Phurit",
    lastName: "Charoenwong",
    birthDate: "2008-09-15",
    primaryPosition: "SMALL_FORWARD",
    secondaryPosition: "POWER_FORWARD",
    heightCm: 194,
    weightKg: 88,
    wingspanCm: 202,
    standingReachCm: 252,
    schoolOrClub: "Assumption College Thonburi",
    province: "Bangkok",
    jerseyNumber: 13,
    bio: "Versatile 3-and-D wing capable of guarding 1 through 4. Explosive transition finisher.",
    avatarUrl: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-ACT-013",
  },
  "ath-11": {
    id: "ath-11",
    userId: "usr-11",
    firstName: "Teerawat",
    lastName: "Prasertkul",
    birthDate: "2007-11-03",
    primaryPosition: "POWER_FORWARD",
    secondaryPosition: "CENTER",
    heightCm: 199,
    weightKg: 94,
    wingspanCm: 206,
    standingReachCm: 258,
    schoolOrClub: "Suankularb Wittayalai",
    province: "Nonthaburi",
    jerseyNumber: 34,
    bio: "Physical paint enforcer, elite offensive rebounder and rim protector with soft midrange touch.",
    avatarUrl: "https://images.unsplash.com/photo-1519766304817-4f37bda74a29?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-SK-034",
  },
  "ath-5": {
    id: "ath-5",
    userId: "usr-5",
    firstName: "Bhuripat",
    lastName: "Pongsakorn",
    birthDate: "2007-06-25",
    primaryPosition: "CENTER",
    heightCm: 204,
    weightKg: 102,
    wingspanCm: 213,
    standingReachCm: 270,
    schoolOrClub: "Chiang Mai University Demonstration",
    province: "Chiang Mai",
    jerseyNumber: 15,
    bio: "Premier rim protector in Northern Thailand. Double-double machine with 2.8 BPG.",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-CMU-015",
  },
  "ath-3": {
    id: "ath-3",
    userId: "usr-3",
    firstName: "Kittipong",
    lastName: "Rattanachai",
    birthDate: "2008-03-10",
    primaryPosition: "SMALL_FORWARD",
    heightCm: 195,
    weightKg: 86,
    wingspanCm: 201,
    standingReachCm: 254,
    schoolOrClub: "Bangkok Christian College",
    province: "Bangkok",
    jerseyNumber: 24,
    bio: "Versatile two-way wing with smooth shooting stroke.",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-BCC-024",
  },
  "ath-4": {
    id: "ath-4",
    userId: "usr-4",
    firstName: "Warit",
    lastName: "Singhavat",
    birthDate: "2007-12-05",
    primaryPosition: "POWER_FORWARD",
    heightCm: 198,
    weightKg: 91,
    wingspanCm: 205,
    standingReachCm: 257,
    schoolOrClub: "Bangkok Christian College",
    province: "Bangkok",
    jerseyNumber: 33,
    bio: "Athletic power forward with high motor and strong paint finishing.",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-BCC-033",
  },
  "ath-2": {
    id: "ath-2",
    userId: "usr-2",
    firstName: "Chayanon",
    lastName: "Wattana",
    birthDate: "2008-05-18",
    primaryPosition: "SHOOTING_GUARD",
    heightCm: 188,
    weightKg: 79,
    wingspanCm: 194,
    standingReachCm: 243,
    schoolOrClub: "Bangkok Christian College",
    province: "Bangkok",
    jerseyNumber: 11,
    bio: "Sharp shooter with quick release and high basketball IQ.",
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-BCC-011",
  },
  "ath-9": {
    id: "ath-9",
    userId: "usr-9",
    firstName: "Piyawat",
    lastName: "Intarasingh",
    birthDate: "2008-07-22",
    primaryPosition: "POINT_GUARD",
    heightCm: 181,
    weightKg: 73,
    wingspanCm: 187,
    standingReachCm: 235,
    schoolOrClub: "Debsirin School",
    province: "Bangkok",
    jerseyNumber: 3,
    bio: "Speedy floor leader with elite vision and defensive tenacity.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-DS-003",
  },
  "ath-14": {
    id: "ath-14",
    userId: "usr-14",
    firstName: "Chavalit",
    lastName: "Chantachote",
    birthDate: "2009-02-14",
    primaryPosition: "POINT_GUARD",
    heightCm: 182,
    weightKg: 74,
    wingspanCm: 189,
    standingReachCm: 236,
    schoolOrClub: "Chonburi Sports School",
    province: "Chonburi",
    jerseyNumber: 8,
    bio: "Eastern region top guard prospect with sharp decision making.",
    avatarUrl: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-CSS-008",
  },
  "ath-15": {
    id: "ath-15",
    userId: "usr-15",
    firstName: "Ratchanon",
    lastName: "Prakorbporn",
    birthDate: "2008-08-30",
    primaryPosition: "POWER_FORWARD",
    heightCm: 197,
    weightKg: 92,
    wingspanCm: 204,
    standingReachCm: 256,
    schoolOrClub: "Suranaree Wittaya",
    province: "Nakhon Ratchasima",
    jerseyNumber: 21,
    bio: "Strong inside presence and tenacious rebounder in the Northeast circuit.",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-SRW-021",
  },
  "ath-16": {
    id: "ath-16",
    userId: "usr-16",
    firstName: "Somkid",
    lastName: "Saelim",
    birthDate: "2006-11-19",
    primaryPosition: "CENTER",
    heightCm: 201,
    weightKg: 98,
    wingspanCm: 209,
    standingReachCm: 265,
    schoolOrClub: "Phuket Wittayalai",
    province: "Phuket",
    jerseyNumber: 42,
    bio: "Dominant southern center with soft touch around the rim.",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-PKW-042",
  },
  "ath-17": {
    id: "ath-17",
    userId: "usr-17",
    firstName: "Jakkarin",
    lastName: "Wannasri",
    birthDate: "2008-04-05",
    primaryPosition: "SHOOTING_GUARD",
    heightCm: 187,
    weightKg: 80,
    wingspanCm: 193,
    standingReachCm: 242,
    schoolOrClub: "Hatyaiwittayalai School",
    province: "Songkhla",
    jerseyNumber: 5,
    bio: "Clutch shooter and fast-break finisher from Songkhla.",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-HYW-005",
  },
  "ath-6": {
    id: "ath-6",
    userId: "usr-6",
    firstName: "Saran",
    lastName: "Thongprasert",
    birthDate: "2008-06-14",
    primaryPosition: "POINT_GUARD",
    heightCm: 180,
    weightKg: 72,
    wingspanCm: 186,
    standingReachCm: 234,
    schoolOrClub: "Hatyaiwittayalai",
    province: "Songkhla",
    jerseyNumber: 6,
    bio: "Lightning-quick floor leader from Southern Thailand with 6.8 APG and elite court vision.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-HYW-006",
  },
  "ath-7": {
    id: "ath-7",
    userId: "usr-7",
    firstName: "Nutdanai",
    lastName: "Klinhom",
    birthDate: "2008-09-02",
    primaryPosition: "SHOOTING_GUARD",
    heightCm: 185,
    weightKg: 77,
    wingspanCm: 190,
    standingReachCm: 239,
    schoolOrClub: "Bangkok Christian College",
    province: "Bangkok",
    jerseyNumber: 9,
    bio: "Reliable perimeter shooter and perimeter defender for BCC.",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    tcasReferenceCode: "STC-VERIFIED-TH-BCC-009",
  },
};

export const mockLeaderboardAthletes: AthleteSeasonStats[] = [
  {
    athleteId: "ath-1",
    firstName: "Thanakorn",
    lastName: "Siriphan",
    jerseyNumber: 7,
    schoolOrClub: "Bangkok Christian College",
    province: "Bangkok",
    position: "POINT_GUARD",
    ageCategory: "U18",
    heightCm: 184,
    weightKg: 76,
    lastAttended: "Bangkok Christian College",
    country: "Thailand",
    avatarUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=400&q=80",
    gamesPlayed: 10,
    points: 214,
    rebounds: 58,
    assists: 76,
    steals: 28,
    blocks: 6,
    turnovers: 24,
    fouls: 18,
    fgMade: 78,
    fgMissed: 70,
    ftMade: 36,
    ftMissed: 8,
    fg3Made: 22,
    fg3Missed: 35,
    eff: 280,
    effPerGame: 28.0,
    efgPct: 60.1,
    tsPct: 63.9,
    astToRatio: 3.17,
    per: 27.6,
    ppg: 21.4,
    rpg: 5.8,
    apg: 7.6,
    spg: 2.8,
    bpg: 0.6,
    fgPct: 52.7,
    ftPct: 81.8,
    scoringRating: 88,
    playmakingRating: 95,
    defenseRating: 84,
    athleticismRating: 86,
  },
  {
    athleteId: "ath-8",
    firstName: "Nattapat",
    lastName: "Sukprasert",
    jerseyNumber: 23,
    schoolOrClub: "Debsirin School",
    province: "Bangkok",
    position: "SHOOTING_GUARD",
    ageCategory: "U18",
    heightCm: 189,
    weightKg: 82,
    lastAttended: "Debsirin School",
    country: "Thailand",
    avatarUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=400&q=80",
    gamesPlayed: 10,
    points: 248,
    rebounds: 62,
    assists: 41,
    steals: 22,
    blocks: 9,
    turnovers: 26,
    fouls: 21,
    fgMade: 92,
    fgMissed: 84,
    ftMade: 40,
    ftMissed: 10,
    fg3Made: 31,
    fg3Missed: 49,
    eff: 262,
    effPerGame: 26.2,
    efgPct: 61.1,
    tsPct: 62.6,
    astToRatio: 1.58,
    per: 26.2,
    ppg: 24.8,
    rpg: 6.2,
    apg: 4.1,
    spg: 2.2,
    bpg: 0.9,
    fgPct: 52.3,
    ftPct: 80.0,
    scoringRating: 96,
    playmakingRating: 78,
    defenseRating: 80,
    athleticismRating: 90,
  },
  {
    athleteId: "ath-10",
    firstName: "Phurit",
    lastName: "Charoenwong",
    jerseyNumber: 13,
    schoolOrClub: "Assumption College Thonburi",
    province: "Bangkok",
    position: "SMALL_FORWARD",
    ageCategory: "U18",
    heightCm: 194,
    weightKg: 88,
    lastAttended: "Assumption College Thonburi",
    country: "Thailand",
    avatarUrl: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=400&q=80",
    gamesPlayed: 9,
    points: 178,
    rebounds: 74,
    assists: 38,
    steals: 19,
    blocks: 14,
    turnovers: 19,
    fouls: 20,
    fgMade: 68,
    fgMissed: 62,
    ftMade: 26,
    ftMissed: 9,
    fg3Made: 16,
    fg3Missed: 32,
    eff: 233,
    effPerGame: 25.9,
    efgPct: 58.5,
    tsPct: 61.2,
    astToRatio: 2.0,
    per: 24.1,
    ppg: 19.8,
    rpg: 8.2,
    apg: 4.2,
    spg: 2.1,
    bpg: 1.6,
    fgPct: 52.3,
    ftPct: 74.3,
    scoringRating: 86,
    playmakingRating: 75,
    defenseRating: 91,
    athleticismRating: 92,
  },
  {
    athleteId: "ath-11",
    firstName: "Teerawat",
    lastName: "Prasertkul",
    jerseyNumber: 34,
    schoolOrClub: "Suankularb Wittayalai",
    province: "Nonthaburi",
    position: "POWER_FORWARD",
    ageCategory: "U18",
    heightCm: 199,
    weightKg: 94,
    lastAttended: "Suankularb Wittayalai",
    country: "Thailand",
    avatarUrl: "https://images.unsplash.com/photo-1519766304817-4f37bda74a29?auto=format&fit=crop&w=400&q=80",
    gamesPlayed: 10,
    points: 192,
    rebounds: 114,
    assists: 24,
    steals: 14,
    blocks: 22,
    turnovers: 21,
    fouls: 25,
    fgMade: 76,
    fgMissed: 58,
    ftMade: 32,
    ftMissed: 14,
    fg3Made: 8,
    fg3Missed: 18,
    eff: 273,
    effPerGame: 27.3,
    efgPct: 59.7,
    tsPct: 62.2,
    astToRatio: 1.14,
    per: 25.8,
    ppg: 19.2,
    rpg: 11.4,
    apg: 2.4,
    spg: 1.4,
    bpg: 2.2,
    fgPct: 56.7,
    ftPct: 69.6,
    scoringRating: 84,
    playmakingRating: 62,
    defenseRating: 94,
    athleticismRating: 94,
  },
  {
    athleteId: "ath-5",
    firstName: "Bhuripat",
    lastName: "Pongsakorn",
    jerseyNumber: 15,
    schoolOrClub: "Chiang Mai University Demonstration",
    province: "Chiang Mai",
    position: "CENTER",
    ageCategory: "U18",
    heightCm: 204,
    weightKg: 102,
    lastAttended: "Chiang Mai University Demonstration",
    country: "Thailand",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    gamesPlayed: 9,
    points: 172,
    rebounds: 128,
    assists: 18,
    steals: 9,
    blocks: 28,
    turnovers: 22,
    fouls: 24,
    fgMade: 71,
    fgMissed: 49,
    ftMade: 30,
    ftMissed: 18,
    fg3Made: 0,
    fg3Missed: 3,
    eff: 266,
    effPerGame: 29.6,
    efgPct: 59.2,
    tsPct: 60.9,
    astToRatio: 0.82,
    per: 26.9,
    ppg: 19.1,
    rpg: 14.2,
    apg: 2.0,
    spg: 1.0,
    bpg: 3.1,
    fgPct: 59.2,
    ftPct: 62.5,
    scoringRating: 82,
    playmakingRating: 54,
    defenseRating: 98,
    athleticismRating: 91,
  },
  {
    athleteId: "ath-3",
    firstName: "Kittipong",
    lastName: "Rattanachai",
    jerseyNumber: 24,
    schoolOrClub: "Bangkok Christian College",
    province: "Bangkok",
    position: "SMALL_FORWARD",
    ageCategory: "U18",
    heightCm: 195,
    weightKg: 86,
    lastAttended: "Bangkok Christian College",
    country: "Thailand",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    gamesPlayed: 10,
    points: 168,
    rebounds: 65,
    assists: 34,
    steals: 16,
    blocks: 11,
    turnovers: 18,
    fouls: 19,
    fgMade: 64,
    fgMissed: 58,
    ftMade: 22,
    ftMissed: 6,
    fg3Made: 18,
    fg3Missed: 38,
    eff: 212,
    effPerGame: 21.2,
    efgPct: 59.8,
    tsPct: 62.5,
    astToRatio: 1.89,
    per: 21.4,
    ppg: 16.8,
    rpg: 6.5,
    apg: 3.4,
    spg: 1.6,
    bpg: 1.1,
    fgPct: 52.5,
    ftPct: 78.6,
    scoringRating: 80,
    playmakingRating: 72,
    defenseRating: 82,
    athleticismRating: 85,
  },
  {
    athleteId: "ath-2",
    firstName: "Chayanon",
    lastName: "Wattana",
    jerseyNumber: 11,
    schoolOrClub: "Bangkok Christian College",
    province: "Bangkok",
    position: "SHOOTING_GUARD",
    ageCategory: "U18",
    heightCm: 188,
    weightKg: 79,
    lastAttended: "Bangkok Christian College",
    country: "Thailand",
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80",
    gamesPlayed: 10,
    points: 154,
    rebounds: 45,
    assists: 36,
    steals: 18,
    blocks: 5,
    turnovers: 17,
    fouls: 18,
    fgMade: 58,
    fgMissed: 52,
    ftMade: 20,
    ftMissed: 5,
    fg3Made: 18,
    fg3Missed: 40,
    eff: 184,
    effPerGame: 18.4,
    efgPct: 60.9,
    tsPct: 63.6,
    astToRatio: 2.12,
    per: 20.1,
    ppg: 15.4,
    rpg: 4.5,
    apg: 3.6,
    spg: 1.8,
    bpg: 0.5,
    fgPct: 52.7,
    ftPct: 80.0,
    scoringRating: 79,
    playmakingRating: 74,
    defenseRating: 79,
    athleticismRating: 82,
  },
  {
    athleteId: "ath-9",
    firstName: "Piyawat",
    lastName: "Intarasingh",
    jerseyNumber: 3,
    schoolOrClub: "Debsirin School",
    province: "Bangkok",
    position: "POINT_GUARD",
    ageCategory: "U18",
    heightCm: 181,
    weightKg: 73,
    lastAttended: "Debsirin School",
    country: "Thailand",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    gamesPlayed: 9,
    points: 126,
    rebounds: 38,
    assists: 59,
    steals: 21,
    blocks: 3,
    turnovers: 20,
    fouls: 22,
    fgMade: 47,
    fgMissed: 48,
    ftMade: 21,
    ftMissed: 7,
    fg3Made: 11,
    fg3Missed: 29,
    eff: 172,
    effPerGame: 19.1,
    efgPct: 55.3,
    tsPct: 58.7,
    astToRatio: 2.95,
    per: 19.3,
    ppg: 14.0,
    rpg: 4.2,
    apg: 6.6,
    spg: 2.3,
    bpg: 0.3,
    fgPct: 49.5,
    ftPct: 75.0,
    scoringRating: 74,
    playmakingRating: 90,
    defenseRating: 82,
    athleticismRating: 80,
  },
  {
    athleteId: "ath-14",
    firstName: "Chavalit",
    lastName: "Chantachote",
    jerseyNumber: 8,
    schoolOrClub: "Chonburi Sports School",
    province: "Chonburi",
    position: "POINT_GUARD",
    ageCategory: "U16",
    heightCm: 182,
    weightKg: 74,
    lastAttended: "Chonburi Sports School",
    country: "Thailand",
    avatarUrl: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=400&q=80",
    gamesPlayed: 8,
    points: 144,
    rebounds: 32,
    assists: 52,
    steals: 19,
    blocks: 4,
    turnovers: 16,
    fouls: 14,
    fgMade: 52,
    fgMissed: 46,
    ftMade: 26,
    ftMissed: 6,
    fg3Made: 14,
    fg3Missed: 33,
    eff: 183,
    effPerGame: 22.9,
    efgPct: 60.2,
    tsPct: 64.2,
    astToRatio: 3.25,
    per: 22.8,
    ppg: 18.0,
    rpg: 4.0,
    apg: 6.5,
    spg: 2.4,
    bpg: 0.5,
    fgPct: 53.1,
    ftPct: 81.3,
    scoringRating: 84,
    playmakingRating: 91,
    defenseRating: 81,
    athleticismRating: 85,
  },
  {
    athleteId: "ath-15",
    firstName: "Ratchanon",
    lastName: "Prakorbporn",
    jerseyNumber: 21,
    schoolOrClub: "Suranaree Wittaya",
    province: "Nakhon Ratchasima",
    position: "POWER_FORWARD",
    ageCategory: "U18",
    heightCm: 197,
    weightKg: 92,
    lastAttended: "Suranaree Wittaya",
    country: "Thailand",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80",
    gamesPlayed: 9,
    points: 162,
    rebounds: 98,
    assists: 22,
    steals: 12,
    blocks: 18,
    turnovers: 19,
    fouls: 22,
    fgMade: 65,
    fgMissed: 52,
    ftMade: 24,
    ftMissed: 11,
    fg3Made: 8,
    fg3Missed: 22,
    eff: 230,
    effPerGame: 25.6,
    efgPct: 59.0,
    tsPct: 61.2,
    astToRatio: 1.16,
    per: 23.3,
    ppg: 18.0,
    rpg: 10.9,
    apg: 2.4,
    spg: 1.3,
    bpg: 2.0,
    fgPct: 55.6,
    ftPct: 68.6,
    scoringRating: 82,
    playmakingRating: 60,
    defenseRating: 90,
    athleticismRating: 91,
  },
  {
    athleteId: "ath-16",
    firstName: "Somkid",
    lastName: "Saelim",
    jerseyNumber: 42,
    schoolOrClub: "Phuket Wittayalai",
    province: "Phuket",
    position: "CENTER",
    ageCategory: "Open",
    heightCm: 201,
    weightKg: 98,
    lastAttended: "Phuket Wittayalai",
    country: "Thailand",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    gamesPlayed: 8,
    points: 136,
    rebounds: 104,
    assists: 14,
    steals: 8,
    blocks: 24,
    turnovers: 17,
    fouls: 21,
    fgMade: 56,
    fgMissed: 44,
    ftMade: 24,
    ftMissed: 14,
    fg3Made: 0,
    fg3Missed: 2,
    eff: 211,
    effPerGame: 26.4,
    efgPct: 56.0,
    tsPct: 58.3,
    astToRatio: 0.82,
    per: 23.5,
    ppg: 17.0,
    rpg: 13.0,
    apg: 1.8,
    spg: 1.0,
    bpg: 3.0,
    fgPct: 56.0,
    ftPct: 63.2,
    scoringRating: 78,
    playmakingRating: 50,
    defenseRating: 95,
    athleticismRating: 88,
  },
  {
    athleteId: "ath-17",
    firstName: "Jakkarin",
    lastName: "Wannasri",
    jerseyNumber: 5,
    schoolOrClub: "Hatyaiwittayalai School",
    province: "Songkhla",
    position: "SHOOTING_GUARD",
    ageCategory: "U18",
    heightCm: 187,
    weightKg: 80,
    lastAttended: "Hatyaiwittayalai School",
    country: "Thailand",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
    gamesPlayed: 9,
    points: 189,
    rebounds: 48,
    assists: 32,
    steals: 17,
    blocks: 6,
    turnovers: 20,
    fouls: 17,
    fgMade: 70,
    fgMissed: 68,
    ftMade: 27,
    ftMissed: 7,
    fg3Made: 22,
    fg3Missed: 48,
    eff: 197,
    effPerGame: 21.9,
    efgPct: 58.7,
    tsPct: 61.8,
    astToRatio: 1.60,
    per: 21.0,
    ppg: 21.0,
    rpg: 5.3,
    apg: 3.6,
    spg: 1.9,
    bpg: 0.7,
    fgPct: 50.7,
    ftPct: 79.4,
    scoringRating: 90,
    playmakingRating: 72,
    defenseRating: 77,
    athleticismRating: 84,
  },
];

export const mockMarketplaceItems: MarketplaceItem[] = [
  {
    id: "item-kobe6",
    sellerId: "ath-1",
    sellerName: "Thanakorn Siriphan",
    sellerSchool: "Bangkok Christian College",
    isSellerVerified: true,
    isProSeller: true,
    title: "Nike Kobe 6 Protro 'Reverse Grinch'",
    brand: "Nike",
    model: "Kobe 6 Protro",
    size: "10.5 US / 44.5 EU",
    condition: "Mint 9.5/10",
    priceThb: 7500,
    isSold: false,
    category: "Footwear",
    cardBgColor: "#af101a",
    imageUrls: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBvVU0ZnR89JalsbHOXlLNY1kFFxq-Yxo5ALb2fhKD5Ks0OJox4-zqEI0OM8bbqyEPXKdL9Ub1VBpUaKR02hyfSdCiyTBupnbFRRxP6Ns-U6TIYFZPb1JaBk-Pz7iIc1wprdI_kmotXYVqg5hy6azvCxECyvXGb1RA0gh1oNAuwSuLJeJ_U_LBDJF0CN-c_cUvRhSZr0WEqWrBJi76xUoH6mrEcT53cuSsrZaPTpHjjb9_yhbvmz79x3Q",
    ],
    wornByAthletes: [
      {
        id: "ath-1",
        name: "Thanakorn Siriphan",
        team: "Bangkok Christian College",
        jerseyNumber: 7,
        position: "POINT_GUARD",
      },
      {
        id: "ath-8",
        name: "Nattapat Sukprasert",
        team: "Debsirin School",
        jerseyNumber: 23,
        position: "SHOOTING_GUARD",
      },
    ],
    createdAt: "2026-09-20T10:00:00Z",
  },
  {
    id: "item-gtcut3",
    sellerId: "ath-8",
    sellerName: "Nattapat Sukprasert",
    sellerSchool: "Debsirin School",
    isSellerVerified: true,
    isProSeller: false,
    title: "Nike Air Zoom G.T. Cut 3 'Summit White/Picante Red'",
    brand: "Nike",
    model: "Air Zoom G.T. Cut 3",
    size: "11.0 US / 45 EU",
    condition: "Brand New",
    priceThb: 6200,
    isSold: false,
    category: "Footwear",
    cardBgColor: "#5cb3d4",
    imageUrls: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCBhvjmaX-AY5CT_lLYDNfL9aWZ8MTENGYfwEx-E3zICOdgbHh1yl0XUmprmawdM_OZSDfIlL6pgj2Wj-t3oR5ivUoEeP2q2wxnbHJodBMDGjstVnxqc8bSqMiPuCuYpgFkOIo4kRCmz65ed6dbhrvIZ7vjlBnczz74JRXRzwzEsdeyicxic8NT9RDs9-dxuN51zBkY5N2ZpSql9h5hwOq-hM8_omaDBpMfPdoFJNcCSmJaNxC4ygEIyg",
    ],
    wornByAthletes: [
      {
        id: "ath-8",
        name: "Nattapat Sukprasert",
        team: "Debsirin School",
        jerseyNumber: 23,
        position: "SHOOTING_GUARD",
      },
    ],
    createdAt: "2026-09-21T08:30:00Z",
  },
  {
    id: "item-sabrina2",
    sellerId: "ath-2",
    sellerName: "Chayanon Wattana",
    sellerSchool: "Bangkok Christian College",
    isSellerVerified: true,
    isProSeller: true,
    title: "Nike Sabrina 2 'Conductor'",
    brand: "Nike",
    model: "Sabrina 2",
    size: "9.5 US / 43 EU",
    condition: "Brand New",
    priceThb: 4600,
    isSold: false,
    category: "Footwear",
    cardBgColor: "#dfd6f3",
    imageUrls: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuC5e_Tzlr-QFIm4GbzTqBfSs9BhXHANnrLWP36CnKSuXnXqLqe-E7NFzpWnCpKH8QyIDAOM3qT-Z6S-01Prz4BoEh3yvQS5Lt5_XvufQRLNQ5jTKWqtlffROU-d5Jpk9StBiRq4dohi29QcXf66-GNFWkerP30yT1HUmlXO2kuoA3e75cRh4rAxd4L8jW0wGn82DNtG2KFIVfFFSh73YVaJJNo1xmn2J44p7jUPl5KQTUlpeeZm2fK19Q",
    ],
    wornByAthletes: [
      {
        id: "ath-2",
        name: "Chayanon Wattana",
        team: "Bangkok Christian College",
        jerseyNumber: 11,
        position: "SHOOTING_GUARD",
      },
      {
        id: "ath-9",
        name: "Piyawat Intarasingh",
        team: "Debsirin School",
        jerseyNumber: 3,
        position: "POINT_GUARD",
      },
    ],
    createdAt: "2026-09-19T16:20:00Z",
  },
  {
    id: "item-zamst-a2dx",
    sellerId: "ath-11",
    sellerName: "Teerawat Prasertkul",
    sellerSchool: "Suankularb Wittayalai",
    isSellerVerified: true,
    isProSeller: false,
    title: "Zamst A2-DX Ankle Brace (High Stability Pair L/R)",
    brand: "Zamst",
    model: "A2-DX Professional",
    size: "L (Men 9.5-12 US)",
    condition: "Mint 9.5/10",
    priceThb: 2800,
    isSold: false,
    category: "Protective Braces",
    cardBgColor: "#e5eeff",
    imageUrls: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDE_wtxJ1gEt-yBj2Ygqwrb7dNGW119_g0GJSucKOA3lWgV1phldyMV_HZPRulefoCpYPZrFmNtUimXiXxCmE-GHVRAoAhF8D7agPrGVQ4rgnV_bTJd_oZ-nLwX5W9qvdAg9AHYwTQAMpWFs_Ez7OKSGgK2KOs0Z0zylC82oY44tR2_It__bdTmkqlW9P1i9Io9owzjXoxHvlURsCmhF1YmoWvMrXeqArIU_VvQ42RokLEjzZkOdgs89w",
    ],
    wornByAthletes: [
      {
        id: "ath-11",
        name: "Teerawat Prasertkul",
        team: "Suankularb Wittayalai",
        jerseyNumber: 34,
        position: "POWER_FORWARD",
      },
      {
        id: "ath-5",
        name: "Bhuripat Pongsakorn",
        team: "Chiang Mai University Demo",
        jerseyNumber: 15,
        position: "CENTER",
      },
    ],
    createdAt: "2026-09-18T11:45:00Z",
  },
  {
    id: "item-mcdavid-hex",
    sellerId: "ath-10",
    sellerName: "Phurit Charoenwong",
    sellerSchool: "Assumption College Thonburi",
    isSellerVerified: true,
    isProSeller: true,
    title: "McDavid HEX Leg Sleeves / Knee Pads (Pair)",
    brand: "McDavid",
    model: "HEX 6446 Extended",
    size: "M (14-16 inch circumference)",
    condition: "Good 8.5/10",
    priceThb: 1450,
    isSold: false,
    category: "Protective Braces",
    cardBgColor: "#dce9ff",
    imageUrls: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBAsdYEeNtvPz_YMSKHxXMMjO4tDX846Kms9lDjNjYQYJJgcIBclwEBPN42JBkmQ-0pDBtHalND6ae7jTu7ziMTZSSXEwBdf8-P8qAPe1LzlU0cClZ3u2ZEz-mCzjF_qMCUbI6Ab5aXH22spQnVl0uRlS9Ju56725396wDJYp3ViBwRpRIh29h72DtbHmlKMYMe4c8s7BiEaLnr6LZ6DN7mPFNK-hQLi9_J2Im8nKxcdYqyN73wyT3Lew",
    ],
    wornByAthletes: [
      {
        id: "ath-10",
        name: "Phurit Charoenwong",
        team: "Assumption College Thonburi",
        jerseyNumber: 13,
        position: "SMALL_FORWARD",
      },
    ],
    createdAt: "2026-09-17T14:10:00Z",
  },
  {
    id: "item-ds-jersey",
    sellerId: "ath-8",
    sellerName: "Nattapat Sukprasert",
    sellerSchool: "Debsirin School",
    isSellerVerified: true,
    isProSeller: false,
    title: "Debsirin High School Official Match Jersey #23 (Authentic Issue)",
    brand: "Grand Sport",
    model: "Debsirin Varsity Player Edition",
    size: "XL",
    condition: "Mint 9.5/10",
    priceThb: 1850,
    isSold: false,
    category: "Uniforms",
    cardBgColor: "#e5eeff",
    imageUrls: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCPvxOvzIQ1acMLjzM5x7jSivkX-lJVsQZVCtg5nu5c6R5GQafaoHRZ38q_Ev9vfSrvBQ5X7ZILuh0y4WQpL16nG2HwUM6EbDJ9zAyiPW7nzRTktCVE-CoknDfdngi_kQwbh5hDtF4W8fgbHtm2y1NiJVCRh_kUtk5UP_rEg6y8Ju3PKkhX3fr5oTBTjriHov0iFdnV1ofR_7zHHrqDTFE_XG1L5qNRaM1YmL0nfaoXf-g2_dz8w2_t2g",
    ],
    wornByAthletes: [
      {
        id: "ath-8",
        name: "Nattapat Sukprasert",
        team: "Debsirin School",
        jerseyNumber: 23,
        position: "SHOOTING_GUARD",
      },
    ],
    createdAt: "2026-09-16T09:00:00Z",
  },
];
